### ISSUE TITLE
国际服6.4版本，抛出ReadWriteMemoryException

### ISSUE THREAD

**Issue by stu4355226** [Natsukage/PostNamazu#40]
目前是用postnamazu的標點功能, 一用就直接crash了

log 發現有以下exception:
ReadWriteMemoryException

還有ArgumentOutOfRangeException 在Setup 可能也有關聯

以下是log
-------------------------------------------------------------
[16:26:28] 插件版本:1.3.2.5
[16:26:28] 在10388端口启动监听
[16:26:28] 绑定Triggernometry
[16:26:28] 绑定OverlayPlugin
[16:28:26] Getting Offsets......
[16:28:26] 已找到FFXIV进程 53304
**[16:28:26] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.**
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[16:29:52] Getting Offsets......
[16:29:52] 已找到FFXIV进程 49360
[16:29:52] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[16:34:45] Getting Offsets......
[16:34:45] 已找到FFXIV进程 39776
[16:34:45] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[16:41:32] Getting Offsets......
[16:41:32] 已找到FFXIV进程 46520
[16:41:33] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[17:27:55] Getting Offsets......
[17:27:56] 已找到FFXIV进程 51980
[17:27:56] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[18:09:13] Getting Offsets......
[18:09:13] 已找到FFXIV进程 20440
[18:09:13] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[19:17:39] /mk off <1>
[19:17:39] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   at GreyMagic.Executor.WaitForInjection(Int32 timeout)
   at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   at GreyMagic.Executor.Execute(Byte[] bytes)
   at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <2>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <3>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <4>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <5>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <6>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <7>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:17:39] /mk off <8>
[19:17:39] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[19:18:13] Getting Offsets......
[19:18:14] 已找到FFXIV进程 13736
[19:18:14] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[19:21:01] Getting Offsets......
[19:21:01] 已找到FFXIV进程 31596
[19:21:01] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()

**Comment by Natsukage** [comment]
看日志应该是6.4的改动导致Command的特征变了，后面会再看看。
日志里看到的都是Command的报错，包括其中执行/mk off指令时的报错。这里说的一用就crash是指进行标点后游戏会崩掉吗？还是说仅仅只是游戏里标点操作没有反应？

**Comment by stu4355226** [comment]
ArgumentOutOfRangeException出現時遊戲不會崩掉
[18:09:13] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at PostNamazu.Common.SigScanner.ScanText(String pattern)
at PostNamazu.Actions.Command.GetOffsets()
at PostNamazu.Actions.NamazuModule.Setup()

當這個/mk off<1> 時遊戲就會崩掉了
[19:17:39] /mk off <1>
[19:17:39] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
at GreyMagic.Executor.WaitForInjection(Int32 timeout)
at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
at GreyMagic.Executor.Execute(Byte[] bytes)
at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
at PostNamazu.Actions.Command.DoTextCommand(String command)
at PostNamazu.PostNamazu.DoAction(String command, String payload)

**Comment by Natsukage** [comment]
啊，了解了。那应该还是Command的问题。
这里是执行了一个/mk off的宏指令用于清除标记。因为前面没有找到Command，所以这里肯定会出问题。
感谢反馈
