### ISSUE TITLE
使用替换快捷键的功能时报错

### ISSUE THREAD

**Issue by JJJJJuli** [Natsukage/PostNamazu#41]
如题，国际服6.4更新后使用Triggermometry中替换hotbar的触发器会报错，并会导致闪退，且会导致act连接失败。烦请大佬抽空看一下，辛苦了！
此处附上日志：
[08:27:47] 插件版本:1.3.2.5
[08:27:47] 在2019端口启动监听
[08:27:47] 绑定Triggernometry
[08:27:47] 绑定OverlayPlugin
[08:28:26] Getting Offsets......
[08:28:27] 已找到FFXIV进程 25132
[08:28:27] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[08:29:20] /hotbar set "Fountain" 1 2 
[08:29:20] /hotbar set "Devilment" 1 4 
[08:29:20] /hotbar set "Technical Step" 7 2 
[08:29:20] /hotbar set "Fan Dance" 1 7 
[08:29:20] /hotbar set "Cascade" 1 1 
[08:29:20] /hotbar set "Standard Step" 7 3 
[08:29:20] /hotbar set "Flourish" 1 3 
[08:29:22] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   at GreyMagic.Executor.WaitForInjection(Int32 timeout)
   at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   at GreyMagic.Executor.Execute(Byte[] bytes)
   at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1A
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 20
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 21
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] /hotbar set "Fountain" 1 2 
[08:29:23] /hotbar set "Cascade" 1 1 
[08:29:23] /hotbar set "Devilment" 1 4 
[08:29:23] /hotbar set "Fan Dance" 1 7 
[08:29:23] /hotbar set "Flourish" 1 3 
[08:29:23] /hotbar set "Standard Step" 7 3 
[08:29:23] /hotbar set "Technical Step" 7 2 
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1A
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 20
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 21
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:25] Getting Offsets......
[08:29:47] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()

**Comment by JJJJJuli** [comment]
此处附上日志：
[08:27:47] 插件版本:1.3.2.5
[08:27:47] 在2019端口启动监听
[08:27:47] 绑定Triggernometry
[08:27:47] 绑定OverlayPlugin
[08:28:26] Getting Offsets......
[08:28:27] 已找到FFXIV进程 25132
[08:28:27] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()
[08:29:20] /hotbar set "Fountain" 1 2 
[08:29:20] /hotbar set "Devilment" 1 4 
[08:29:20] /hotbar set "Technical Step" 7 2 
[08:29:20] /hotbar set "Fan Dance" 1 7 
[08:29:20] /hotbar set "Cascade" 1 1 
[08:29:20] /hotbar set "Standard Step" 7 3 
[08:29:20] /hotbar set "Flourish" 1 3 
[08:29:22] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   at GreyMagic.Executor.WaitForInjection(Int32 timeout)
   at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   at GreyMagic.Executor.Execute(Byte[] bytes)
   at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1A
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 20
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:22] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 21
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] /hotbar set "Fountain" 1 2 
[08:29:23] /hotbar set "Cascade" 1 1 
[08:29:23] /hotbar set "Devilment" 1 4 
[08:29:23] /hotbar set "Fan Dance" 1 7 
[08:29:23] /hotbar set "Flourish" 1 3 
[08:29:23] /hotbar set "Standard Step" 7 3 
[08:29:23] /hotbar set "Technical Step" 7 2 
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1A
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1C
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 1B
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 20
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:23] ReadWriteMemoryException: Error while writing memory! Access is denied, at addr: 0, Size: 21
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[08:29:25] Getting Offsets......
[08:29:47] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at PostNamazu.Common.SigScanner.ScanText(String pattern)
   at PostNamazu.Actions.Command.GetOffsets()
   at PostNamazu.Actions.NamazuModule.Setup()

**Comment by JJJJJuli** [comment]
![Screenshot 2023-05-24 083121](https://github.com/Natsukage/PostNamazu/assets/133631853/690a418a-146e-4103-b007-4fe8824d940f)
