### ISSUE TITLE
国际服6.4版本 抛出ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by leifengsang** [Natsukage/PostNamazu#42]
> [01:40:09] 插件版本:1.3.2.5
[01:40:09] 在2020端口启动监听
[01:40:09] 绑定Triggernometry
[01:40:09] 绑定OverlayPlugin
[01:40:12] Getting Offsets......
[01:40:13] 已找到FFXIV进程 20316
[01:40:13] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PostNamazu.Common.SigScanner.ScanText(String pattern)
   在 PostNamazu.Actions.Command.GetOffsets()
   在 PostNamazu.Actions.NamazuModule.Setup()

**Comment by leifengsang** [comment]
另外，执行textCommand命令也会报错
>  [01:40:09] 插件版本:1.3.2.5
[01:40:09] 在2020端口启动监听
[01:40:09] 绑定Triggernometry
[01:40:09] 绑定OverlayPlugin
[01:40:12] Getting Offsets......
[01:40:13] 已找到FFXIV进程 20316
[01:40:13] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 PostNamazu.Common.SigScanner.ScanText(String pattern)
   在 PostNamazu.Actions.Command.GetOffsets()
   在 PostNamazu.Actions.NamazuModule.Setup()
[01:41:48] /e current sort rule:SAM/MNK/RPR/DRG/NIN/WAR/DRK/GNB/PLD/BRD/MCH/DNC/BLM/RDM/SMN/WHM/AST/SGE/SCH
[01:41:48] /e D1 RDM Liberated Flame
[01:41:50] System.Exception: Process must have frozen or gotten out of sync: InjectionFinishedEvent was never fired
   at GreyMagic.Executor.WaitForInjection(Int32 timeout)
   at GreyMagic.Executor.ExecuteInternal(Boolean inject, Int32 timeout)
   at GreyMagic.Executor.Execute(Byte[] bytes)
   at GreyMagic.CachedCall.CallInjected64[T](IntPtr address, Object[] args)
   at GreyMagic.ExternalProcessMemory.CallInjected64[T](IntPtr address, Object[] args)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[01:41:50] ReadWriteMemoryException: Error while writing memory! 拒绝访问。, at addr: 0, Size: 19
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)
[01:41:50] /e H1 WHM Shiori Maco
[01:41:50] ReadWriteMemoryException: Error while writing memory! 拒绝访问。, at addr: 0, Size: 15
   at GreyMagic.ExternalProcessMemory.WriteByteBuffer(IntPtr addr, Void* buffer, Int32 count)
   at GreyMagic.AllocatedMemory.WriteBytes(String allocatedName, Byte[] bytes)
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)

**Comment by Natsukage** [comment]
你用的是1.3.2.5版本的邮差了，请更新版本
