### ISSUE TITLE
System.Exception: 没有对应的游戏进程

### ISSUE THREAD

**Issue by HongerZ** [Natsukage/PostNamazu#43]
当我打开 FF 我看到
![image](https://github.com/Natsukage/PostNamazu/assets/134543563/481bd877-f670-49e0-aa17-5802471d5a7d)

[14:18:42] System.Exception: 没有对应的游戏进程
   at PostNamazu.Actions.Command.DoTextCommand(String command)
   at PostNamazu.PostNamazu.DoAction(String command, String payload)

你能帮助我吗? 抱歉，我正在使用 google 翻译

**Comment by Natsukage** [comment]
please use the new release(1.3.2.6) if you are playing 6.4
